### ISSUE TITLE
Documentazione sull' utilizzo del pacchetto

### ISSUE THREAD

**Issue by lorenzomisuri** [offline-agency/laravel-fatture-in-cloud#29]
Vorrei capire, una volta installato e configurato correttamente il pacchetto, in che modo vengono lanciate le api.
Esistente una libreria con delle funzioni? Tramite il codice sono riuscito a trovare solo i modelli.

Potete aiutarmi ?

p.s. al momento sono in fase di analisi quindi non ho ancora né installato il pacchetto né tantomeno fatto dei test in merito

**Comment by Giacomo92** [comment]
Ciao @lorenzomisuri , abbiamo aggiornato la [doc](https://docs.offlineagency.com/laravel-fatture-in-cloud/).

Facci sapere come va, se hai bisogno di supporto scrivici pure
