### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by lorenzomisuri** [offline-agency/laravel-fatture-in-cloud#34]
Sto provando ad installare questa libreria su un progetto Laravel 8, ma in fase di installazione mi comunica il messaggio :
offline-agency/laravel-fatture-in-cloud[2.1.0, ..., 2.1.1] require illuminate/support ^5.8|^6.0  -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8.40).

Io ho attualmente installato Illuminate/Support ^8.40, è possibile aggiornare la libreria, in modo che supporti anche illuminate/support >= 8.0?

Grazie

**Comment by Giacomo92** [comment]
Ciao @lorenzomisuri , ho appena rilasciato la versione 2.2.0 che supporta Laravel 7 e 8.
